### ISSUE TITLE
Pushing to swift as a backend hangs and generates a client exception on the docker registry

### ISSUE THREAD

**Issue by drobison00** [bacongobbler/docker-registry-driver-swift#24]
=== Push side
d56e767abb61: Pushing [=================================================> ] 326.4 MB/326.8 MB 0

(just hangs here, forever)

=== Registry side
29/Jan/2015:18:48:29 +0000 ERROR: Object HEAD failed: https://storage.us2.oraclecloud.com/v1/*******/docker-registry/registry/images/11a37ad47a09812819e6d5634ebcde508e9a49d186b9dc71bbc8885b1b4a2344/layer 404 Not Found
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1208, in _retry
rv = func(self.url, self.token, args, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 874, in head_object
http_response_content=body)
ClientException: Object HEAD failed: https://storage.us2.oraclecloud.com/v1/*******/docker-registry/registry/images/11a37ad47a09812819e6d5634ebcde508e9a49d186b9dc71bbc8885b1b4a2344/layer 404 Not Found

**Comment by bacongobbler** [comment]
Does Oracle Cloud deny HEAD requests? Basically what's happening here is that the registry is trying to figure out the layer size, which it does so through a HEAD request.

**Comment by bacongobbler** [comment]
relevant code: https://github.com/bacongobbler/docker-registry-driver-swift/blob/master/docker_registry/drivers/swift.py#L142-L143

**Comment by drobison00** [comment]
I am able to make the call manually to the same object that is failed on in the message log. I'm guessing there may be some delay in the object becoming visible.

curl -v -X HEAD -H "X-Auth-Token: ************" https://storage.us2.oraclecloud.com/v1/*******/docker-registry/registry/images/11a37ad47a09812819e6d5634ebcde508e9a49d186b9dc71bbc8885b1b4a2344/layer
> HEAD /v1/********/docker-registry/registry/images/11a37ad47a09812819e6d5634ebcde508e9a49d186b9dc71bbc8885b1b4a2344/layer HTTP/1.1
> User-Agent: curl/7.37.1
> Host: storage.us2.oraclecloud.com
> Accept: */*
> X-Auth-Token: **********
> 
< HTTP/1.1 200 OK
< Date: Thu, 29 Jan 2015 20:52:07 GMT
< Content-Length: 273481054
< Accept-Ranges: bytes
< Last-Modified: Thu, 29 Jan 2015 18:48:30 GMT
< Etag: 78c0a36d9580a7d18ccee09a345794a2
< X-Timestamp: 1422557309.89105
< Content-Type: application/octet-stream
< X-Trans-Id: txabe59e99c10143b7820da-0054ca9d77
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Language: en
< 
* transfer closed with 273481054 bytes remaining to read
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):
curl: (18) transfer closed with 273481054 bytes remaining to read

**Comment by drobison00** [comment]
Closing. I misunderstood what the log files were telling me. Some debug messages tagged as Errors don't appear to actually be errors.
