### ISSUE TITLE
HTTP 408 timeout when pushing image

### ISSUE THREAD

**Issue by mimizone** [bacongobbler/docker-registry-driver-swift#26]
I reported more details on the bug here thinking it was related initially
https://github.com/docker/docker-registry/issues/320#issuecomment-73161271

It seems the root cause is either in my config of the swift driver or swift backend.

it returns HTTP 408 timeout when pushing images.
then ultimately the docker client complains about the '<' character, since the swift backend returns HTML.

Some files got through though, I can see them in the swift container.

Would you have any clue of what's going on?

**Comment by bacongobbler** [comment]
It looks like the swift cluster closed the connection on their end. Do you happen to know how large the layer is, as well as how long the connection goes on before it is closed?

For reference, I originally created this project using http://www.hpcloud.com/ as the target provider (HP Public Cloud is a glorified Openstack cluster), so it's possible that there's something off with the swift backend.

**Comment by mimizone** [comment]
the layer is ~180M, it's the default ubuntu image I use for test of the local registry.
my swift backend is also local, actually implemented with ceph.
I pushed files bigger than 200M without problem via both openstack horizon and the swift cli, all over the public internet from my home+vpn to our internal system.

The test with the registry is from our internal network, so speed/latency shouldn't be the issue.
I guess I will have to check the swift logs or even tcpdump...
is there a debug mode for the plugin different than the registry loglevel?

**Comment by bacongobbler** [comment]
There's no debug mode, unfortunately. If you have access to them, I'd inspect any debug logs from swift. That 408 came from swift so I'd start there (or tcpdump, like you said).

**Comment by mimizone** [comment]
the root cause was network related with MTU discrepancy between nodes...
thanks for helping out!

**Comment by qburst-praven** [comment]
hey @mimizone ,

I seem to have run into the same issue. Can you please give some more details on what MTU discrepancy you noticed?

Regards
Praven John

**Comment by bacongobbler** [comment]
Does https://github.com/docker/docker-registry/issues/941 seem relevant, considering that the OP sounded like it's pointing to a related bug?

**Comment by qburst-praven** [comment]
No don't think so, considering the issue u pointed is with docker-registry.
We use the private repos within docker hub, not our own docker registry...

Thanks
Praven John
Q_Burst_
www.qburst.com
skype: praven_john
